name: Node.js CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Save node_modules cache for the next job
      - name: Upload node_modules cache
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: ./node_modules

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build       # waits for build job to complete
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Restore node_modules from build job to avoid reinstalling
      - name: Download node_modules cache
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: ./node_modules

      - name: Run tests
        run: npm test
